Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network", bridge: "inet-sw01-nl"
  config.vm.provision "file", source: "install.sh", destination: "$HOME/install.sh"
  config.vm.provision "shell", inline: "sudo chmod 777 install.sh"
  config.vm.provision "shell", inline: "./install.sh"
  config.vm.network "forwarded_port", guest: 80, host: 8080
end